"""Initial migration.

Revision ID: 7b15b0b8a1e7
Revises: 
Create Date: 2023-08-29 04:19:52.643176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b15b0b8a1e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mac_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user', 'u_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['u_email'])
    op.create_unique_constraint(None, 'user', ['u_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'u_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('mac_address')
    # ### end Alembic commands ###
