"""Initial migration.

Revision ID: dae0b5315822
Revises: 
Create Date: 2023-08-24 05:59:10.377751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae0b5315822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user', 'u_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['u_name'])
    op.create_unique_constraint(None, 'user', ['u_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'u_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('admin', 'is_admin')
    # ### end Alembic commands ###
